apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-manage
  labels:
    app: manage
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 80
    name: bundled
  - port: 8000
    name: unbundled
  selector:
    app: manage
    release: {{ .Release.Name }}
